name: CI Pipeline Odyssey Gate

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code source
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Installer les dépendances
        run: npm install --legacy-peer-deps

      - name: Vérifier le linting
        run: npm run lint

      - name: Lancer les tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Compiler l’application
        run: npm run build --prod
